on:
  push:
    branches:
    - main
    - release/*
jobs:
  my_job:
    name: wc then send to mail
    runs-on: ubuntu-22.04
    steps:
    - name: do wordcount then put output to text file
      run: |
        wc -l ./helloworld.js > /tmp/linesofcode.txt
    - name: Send email
      uses: devellany/send-mail@v1.0.2
      with:
        host: smtp.google.com
        # Optional port (defaults to 465)
        port: 465
        account: ${{secrets.ACCOUNT}}
        password: ${{secrets.MAIL_PASSWORD}}
        sender: devellany
        from: ${{secrets.MAIL_ADDRESS}}
        to: devellay@dico.me
        subject: mail title.
        body: your messages.
      # Optional content type (defaults to text/plain)
        contentType: text/plain
      # Optional attachment files (JSON type. require property 'path')
        attachments: '[{"path":"README.md"}]'
