on:
  workflow_dispatch:
jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['18.x', '20.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node_version }}

    - name: do wordcount then put output to text file
      run: |
        wc -l helloworld.js > /tmp/linesofcode.txt
    - name: Send email
      uses: devellany/send-mailer@v1.0.2
      with:
        host: smtp.google.com
      # Optional port (defaults to 465)
        port: 465
        account: ${{secrets.ACCOUNT}}
        password: ${{secrets.MAIL_PASSWORD}}
        sender: devellany
        from: ${{secrets.MAIL_ADDRESS}}
        to: devellay@dico.me
        subject: mail title.
        body: your messages.
        # Optional content type (defaults to text/plain)
        contentType: text/plain
        # Optional attachment files (JSON type. require property 'path')
        attachments: '[{"path":"/tmp/linesofcode.txt"}]'
